server:
  port: 8083

spring:
  application:
    name: message-broker
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:jobportal}
    password: ${SPRING_RABBITMQ_PASSWORD:jobportal}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.jobportal.messagebroker: INFO
