server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: []

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.jobportal.gateway: DEBUG
